name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: zziwon/flask-devsecops:latest
        
    - name: Run Bandit (Python SAST)
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-report.json || true

    - name: Run Safety (Python SCA)
      run: |
        pip install safety
        safety check --full-report --json > safety-report.json || true

    - name: Run Trivy (Image Scan)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: zziwon/flask-devsecops:latest
        format: json
        output: trivy-report.json
        exit-code: 0
        ignore-unfixed: true

    - name: Run Trivy (Image Scan SARIF)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: zziwon/flask-devsecops:latest
        format: sarif
        output: trivy-report.sarif
        exit-code: 0
        ignore-unfixed: true
        
    - name: Upload Artifact - Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit-report.json

    - name: Upload Artifact - Safety Report
      uses: actions/upload-artifact@v4
      with:
        name: safety-report
        path: safety-report.json

    - name: Upload Artifact - Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report.json

    - name: Upload SARIF report 
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: trivy-report.sarif